"""Isolated exact-byte INEGI CPI calendar and July 2026 fact source.

The source is deliberately disabled, unregistered, and shadow/research only.
It performs no network access or writes.  Every accepted fact is regenerated by
reopening fixed read-only official archives and their exact observation
manifest.  The obsolete ``calendar.xml`` response is retained as a quarantined
later revision and is never used to establish a clock or fact.

The 7 August release is historical availability-counterfactual context because
the cohort first retained it on 17 August.  The 9 September calendar clock was
captured prospectively, but it supports collection only: no consensus,
surprise, direction, proof, promotion, authorization, or execution follows.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import io
import json
import math
import os
import re
import stat
import sys
import unicodedata
import xml.etree.ElementTree as ET
from decimal import Decimal, InvalidOperation
from email.utils import parsedate_to_datetime
from pathlib import Path
from typing import Any, Mapping
from zoneinfo import ZoneInfo

import pypdf


SCHEMA_VERSION = 1
SOURCE_ID = "mxn_inegi_cpi_exact_v1"
CONTRACT_ID = "mxn_inegi_cpi_exact_v1_20260817"
COHORT_ID = "mxn_inegi_cpi_exact_v1_20260817"
TIMEZONE_NAME = "America/Mexico_City"
UTC = dt.timezone.utc
PDF_EXTRACTOR = "pypdf"
PDF_EXTRACTOR_VERSION = "6.15.0"
PYTHON_VERSION = "3.13.14"
PDF_TRANSFORMATION_ID = "pypdf_6_15_0_layout_nfc_lf_rstrip_formfeed_v1"

OBSERVATION_MANIFEST_PATH = (
    "data/oanda_training_manager/source_archives/mxn_inegi_cpi_exact_v1/"
    "source_observation_manifest_v1.json"
)
OBSERVATION_MANIFEST_BYTES = 9_761
OBSERVATION_MANIFEST_SHA256 = (
    "43a30c8bc2daa3a7573062daaf2556f2e3a0bbfdf3a1a0adecc93f2b5a653921"
)

CALENDAR_PDF_URL = (
    "https://www.inegi.org.mx/contenidos/saladeprensa/doc/cal_2026.pdf"
)
JULY_RELEASE_PDF_URL = (
    "https://www.inegi.org.mx/contenidos/saladeprensa/boletines/2026/"
    "inpc/inpc_2q2026_08.pdf"
)
CALENDAR_XML_URL = "https://www.inegi.org.mx/servicios/xml/calendar.xml"

EXPECTED_JULY_FACTS: dict[str, Decimal] = {
    "headline_monthly_pct": Decimal("0.03"),
    "headline_annual_pct": Decimal("3.12"),
    "core_monthly_pct": Decimal("0.23"),
    "core_annual_pct": Decimal("3.95"),
}

EXPECTED_CLOCKS: tuple[dict[str, str], ...] = (
    {
        "event_date": "2026-08-07",
        "reference_period": "2026-07",
        "local_time": "06:00",
        "scheduled_utc": "2026-08-07T12:00:00Z",
        "collection_class": "historical_availability_counterfactual_archive_only",
    },
    {
        "event_date": "2026-09-09",
        "reference_period": "2026-08",
        "local_time": "06:00",
        "scheduled_utc": "2026-09-09T12:00:00Z",
        "collection_class": "prospective_schedule_only",
    },
)

_WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
_ARCHIVE_PREFIX = (
    "data/oanda_training_manager/source_archives/mxn_inegi_cpi_exact_v1/"
)

_ARTIFACT_SPECS: dict[str, dict[str, Any]] = {
    "calendar_pdf": {
        "source_url": CALENDAR_PDF_URL,
        "archive_path": _ARCHIVE_PREFIX + "calendar_2026_eaa5c61f.pdf",
        "bytes": 286_364,
        "sha256": "eaa5c61fe101b80119ab1fadad28d37e8b702fcd586e2b5e311d5da3b91de970",
        "content_type": "application/pdf",
        "role": "authoritative_schedule_anchor",
        "causal_use": "future_clock_only_when_observed_before_event",
        "semantic_valid": True,
        "text_path": (
            _ARCHIVE_PREFIX
            + "calendar_2026_eaa5c61f."
            + PDF_TRANSFORMATION_ID
            + ".txt"
        ),
        "text_bytes": 173_182,
        "text_sha256": "6332e6f8ebe0735ae3fc089b1e4c06c23089a1a93dc88b517485565281ee657d",
        "page_count": 28,
    },
    "july_release_pdf": {
        "source_url": JULY_RELEASE_PDF_URL,
        "archive_path": _ARCHIVE_PREFIX + "july_2026_cpi_release_504f8c9f.pdf",
        "bytes": 290_302,
        "sha256": "504f8c9ff32fc428ba2d39d6ce06dec43343873d8dcab4ec9ba808438d75138a",
        "content_type": "application/pdf",
        "role": "authoritative_historical_release",
        "causal_use": "availability_counterfactual_archive_only",
        "semantic_valid": True,
        "text_path": (
            _ARCHIVE_PREFIX
            + "july_2026_cpi_release_504f8c9f."
            + PDF_TRANSFORMATION_ID
            + ".txt"
        ),
        "text_bytes": 28_951,
        "text_sha256": "b2161f0e03c379ba9708fb81afedefdfbe15d36ad1e504113ea1fb8d4ef27967",
        "page_count": 6,
    },
    "headline_annual_xml": {
        "source_url": "https://www.inegi.org.mx/servicios/xml/INPCA_M_O.xml",
        "archive_path": _ARCHIVE_PREFIX + "INPCA_M_O_e8c36462.xml",
        "bytes": 679,
        "sha256": "e8c36462209e65a08c6d8c8afe79bcc6eb01b96681a5f27b696dcf38955a7b56",
        "content_type": "text/xml",
        "role": "historical_release_corroboration",
        "causal_use": "later_observed_current_snapshot_archive_only",
        "semantic_valid": True,
        "nemonic": "INPCA_M_O",
        "fact_name": "headline_annual_pct",
    },
    "headline_monthly_xml": {
        "source_url": "https://www.inegi.org.mx/servicios/xml/INPCM_M_O.xml",
        "archive_path": _ARCHIVE_PREFIX + "INPCM_M_O_a262c359.xml",
        "bytes": 681,
        "sha256": "a262c35928f3d034b209b1f521c112fc9419a0d1ded1b3c6d5bb385ee3e8b4e0",
        "content_type": "text/xml",
        "role": "historical_release_corroboration",
        "causal_use": "later_observed_current_snapshot_archive_only",
        "semantic_valid": True,
        "nemonic": "INPCM_M_O",
        "fact_name": "headline_monthly_pct",
    },
    "core_annual_xml": {
        "source_url": "https://www.inegi.org.mx/servicios/xml/INPCAS_M_O.xml",
        "archive_path": _ARCHIVE_PREFIX + "INPCAS_M_O_bc61647d.xml",
        "bytes": 703,
        "sha256": "bc61647d7ae366f9c2ba18d7dbc754205fb60899e455bd23ac1876f773471952",
        "content_type": "text/xml",
        "role": "historical_release_corroboration",
        "causal_use": "later_observed_current_snapshot_archive_only",
        "semantic_valid": True,
        "nemonic": "INPCAS_M_O",
        "fact_name": "core_annual_pct",
    },
    "core_monthly_xml": {
        "source_url": "https://www.inegi.org.mx/servicios/xml/INPCMS_M_O.xml",
        "archive_path": _ARCHIVE_PREFIX + "INPCMS_M_O_d5c33c4e.xml",
        "bytes": 705,
        "sha256": "d5c33c4ea9917cec34fc49697f6d1c275fecc2338ca6f1c17f5a98f5b47af5e0",
        "content_type": "text/xml",
        "role": "historical_release_corroboration",
        "causal_use": "later_observed_current_snapshot_archive_only",
        "semantic_valid": True,
        "nemonic": "INPCMS_M_O",
        "fact_name": "core_monthly_pct",
    },
    "calendar_xml_later_revision": {
        "source_url": CALENDAR_XML_URL,
        "archive_path": _ARCHIVE_PREFIX + "calendar_xml_later_revision_4af72939.xml",
        "bytes": 13_370,
        "sha256": "4af72939ac4754fa4016f0321f70562df5fcc4440cb3c70c6908fd524a017629",
        "content_type": "text/html",
        "role": "quarantined_later_observed_revision",
        "causal_use": "forbidden_for_prior_clock_or_proof",
        "semantic_valid": False,
    },
}

_GUARDRAILS: dict[str, Any] = {
    "research_only": True,
    "shadow_only": True,
    "registered_with_live_collector": False,
    "enabled": False,
    "runtime_supported": False,
    "consensus": None,
    "surprise": None,
    "direction": None,
    "currency_bias": None,
    "pair_bias": None,
    "confirmation_eligible": False,
    "proof_eligible": False,
    "promotion_eligible": False,
    "authorization_eligible": False,
    "execution_eligible": False,
    "can_authorize": False,
    "can_place_orders": False,
    "supported_execution_decision": "no_trade",
}


class MxnInegiCpiExactSourceError(RuntimeError):
    """Raised whenever the exact retained-source contract is not proved."""


def _fail(reason: str) -> None:
    raise MxnInegiCpiExactSourceError(reason)


def _canonical_json(value: Any) -> str:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    )


def canonical_sha256(value: Any) -> str:
    return hashlib.sha256(_canonical_json(value).encode("utf-8")).hexdigest()


def _strict_equal(actual: Any, expected: Any) -> bool:
    if type(expected) is dict:
        if type(actual) is not dict or set(actual) != set(expected):
            return False
        return all(_strict_equal(actual[key], value) for key, value in expected.items())
    if type(expected) in (list, tuple):
        if type(actual) not in (list, tuple) or len(actual) != len(expected):
            return False
        return all(_strict_equal(left, right) for left, right in zip(actual, expected))
    if expected is None:
        return actual is None
    return type(actual) is type(expected) and actual == expected


def _strict_json(raw: bytes, *, label: str) -> Any:
    def reject_constant(value: str) -> None:
        _fail(f"{label}_nonfinite_number:{value}")

    def parse_float(value: str) -> float:
        parsed = float(value)
        if not math.isfinite(parsed):
            _fail(f"{label}_nonfinite_number:{value}")
        return parsed

    def unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                _fail(f"{label}_duplicate_key:{key}")
            result[key] = value
        return result

    try:
        return json.loads(
            raw.decode("utf-8"),
            object_pairs_hook=unique_object,
            parse_constant=reject_constant,
            parse_float=parse_float,
        )
    except MxnInegiCpiExactSourceError:
        raise
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        raise MxnInegiCpiExactSourceError(f"{label}_invalid_json") from exc


def _canonical_utc(value: Any, *, label: str) -> dt.datetime:
    if type(value) is not str or not value.endswith("+00:00"):
        _fail(f"{label}_not_exact_utc_string")
    try:
        parsed = dt.datetime.fromisoformat(value)
    except ValueError as exc:
        raise MxnInegiCpiExactSourceError(f"{label}_invalid") from exc
    if parsed.tzinfo != UTC or parsed.isoformat() != value:
        _fail(f"{label}_not_canonical_utc")
    return parsed


def _http_date(value: Any, *, label: str) -> dt.datetime:
    if type(value) is not str:
        _fail(f"{label}_not_string")
    try:
        parsed = parsedate_to_datetime(value)
    except (TypeError, ValueError) as exc:
        raise MxnInegiCpiExactSourceError(f"{label}_invalid") from exc
    if parsed.tzinfo is None:
        _fail(f"{label}_naive")
    return parsed.astimezone(UTC)


def _workspace_path(relative_path: str) -> Path:
    if type(relative_path) is not str:
        _fail("archive_path_not_string")
    relative = Path(relative_path)
    if relative.is_absolute() or ".." in relative.parts:
        _fail("archive_path_not_workspace_relative")
    candidate = (_WORKSPACE_ROOT / relative).absolute()
    try:
        candidate.relative_to(_WORKSPACE_ROOT)
    except ValueError as exc:
        raise MxnInegiCpiExactSourceError("archive_path_escaped_workspace") from exc
    return candidate


def _file_identity(value: os.stat_result) -> tuple[int, int, int, int, int]:
    return (
        int(value.st_dev),
        int(value.st_ino),
        int(value.st_size),
        int(value.st_mtime_ns),
        int(value.st_nlink),
    )


def _assert_no_reparse_components(path: Path) -> None:
    current = Path(path.anchor)
    for part in path.parts[1:]:
        current = current / part
        try:
            value = os.lstat(current)
        except OSError as exc:
            raise MxnInegiCpiExactSourceError("pinned_file_component_missing") from exc
        if stat.S_ISLNK(value.st_mode):
            _fail("pinned_file_symlink_component_forbidden")
        attributes = int(getattr(value, "st_file_attributes", 0))
        reparse = int(getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400))
        if attributes & reparse:
            _fail("pinned_file_reparse_component_forbidden")


def _read_exact_pinned_file(
    path: str | Path,
    *,
    expected_path: str | Path,
    expected_bytes: int,
    expected_sha256: str,
    require_read_only: bool = True,
) -> bytes:
    requested = Path(path).absolute()
    expected = Path(expected_path).absolute()
    if os.path.normcase(str(requested)) != os.path.normcase(str(expected)):
        _fail("pinned_file_path_substitution")
    _assert_no_reparse_components(requested)
    try:
        if requested.resolve(strict=True) != expected.resolve(strict=True):
            _fail("pinned_file_resolved_path_mismatch")
    except OSError as exc:
        raise MxnInegiCpiExactSourceError("pinned_file_missing") from exc
    before = os.lstat(requested)
    if not stat.S_ISREG(before.st_mode):
        _fail("pinned_file_not_regular")
    if before.st_nlink != 1:
        _fail("pinned_file_hardlink_forbidden")
    if require_read_only:
        if os.name == "nt":
            readonly = int(getattr(stat, "FILE_ATTRIBUTE_READONLY", 0x1))
            attributes = int(getattr(before, "st_file_attributes", 0))
            if attributes & readonly == 0:
                _fail("pinned_file_not_read_only")
        elif before.st_mode & (stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH):
            _fail("pinned_file_not_read_only")
    with requested.open("rb") as handle:
        opened_before = os.fstat(handle.fileno())
        if _file_identity(opened_before) != _file_identity(before):
            _fail("pinned_file_swapped_before_open")
        raw = handle.read()
        opened_after = os.fstat(handle.fileno())
    after = os.lstat(requested)
    if _file_identity(opened_before) != _file_identity(opened_after):
        _fail("pinned_file_changed_while_reading")
    if _file_identity(opened_after) != _file_identity(after):
        _fail("pinned_file_path_swapped_after_read")
    if type(expected_bytes) is not int or isinstance(expected_bytes, bool):
        _fail("expected_bytes_not_exact_int")
    if len(raw) != expected_bytes:
        _fail("pinned_file_byte_count_mismatch")
    if type(expected_sha256) is not str or not re.fullmatch(r"[0-9a-f]{64}", expected_sha256):
        _fail("expected_sha256_invalid")
    if hashlib.sha256(raw).hexdigest() != expected_sha256:
        _fail("pinned_file_sha256_mismatch")
    return raw


def _normalized_pdf_text(raw: bytes) -> tuple[bytes, int]:
    if pypdf.__version__ != PDF_EXTRACTOR_VERSION:
        _fail(f"pdf_extractor_version_mismatch:{pypdf.__version__}")
    if sys.version.split()[0] != PYTHON_VERSION:
        _fail(f"python_pdf_runtime_version_mismatch:{sys.version.split()[0]}")
    try:
        reader = pypdf.PdfReader(io.BytesIO(raw), strict=True)
        pages: list[str] = []
        for page in reader.pages:
            text = page.extract_text(extraction_mode="layout") or ""
            text = text.replace("\r\n", "\n").replace("\r", "\n")
            text = "\n".join(line.rstrip(" \t") for line in text.split("\n"))
            pages.append(unicodedata.normalize("NFC", text).strip())
    except Exception as exc:
        raise MxnInegiCpiExactSourceError("pdf_extraction_failed") from exc
    return ("\n\f\n".join(pages).strip() + "\n").encode("utf-8"), len(reader.pages)


_TOP_MANIFEST_FIELDS = frozenset(
    {
        "schema_version",
        "source_id",
        "source_contract_id",
        "source_cohort_id",
        "capture_completed_utc",
        "capture_method",
        "primary_pdf_runtime",
        "calendar_authority",
        "calendar_xml_prior_expected_unretained",
        "optional_historical_xmls_retained",
        "artifacts",
        "policy",
    }
)


def _exact_mapping(value: Any, fields: frozenset[str], *, label: str) -> dict[str, Any]:
    if type(value) is not dict or set(value) != fields:
        _fail(f"{label}_closed_schema_mismatch")
    return value


def _validate_observation_manifest(manifest: Any) -> dict[str, Any]:
    row = _exact_mapping(manifest, _TOP_MANIFEST_FIELDS, label="observation_manifest")
    exact_top = {
        "schema_version": 1,
        "source_id": SOURCE_ID,
        "source_contract_id": CONTRACT_ID,
        "source_cohort_id": COHORT_ID,
        "capture_method": "python_urllib_request_read_all_then_atomic_replace",
        "calendar_authority": "calendar_pdf",
        "optional_historical_xmls_retained": False,
    }
    for key, expected in exact_top.items():
        if not _strict_equal(row[key], expected):
            _fail(f"observation_manifest_value_mismatch:{key}")
    capture_completed = _canonical_utc(
        row["capture_completed_utc"], label="capture_completed_utc"
    )

    runtime = _exact_mapping(
        row["primary_pdf_runtime"],
        frozenset({"extractor", "extractor_version", "python_version", "transformation_id"}),
        label="primary_pdf_runtime",
    )
    expected_runtime = {
        "extractor": PDF_EXTRACTOR,
        "extractor_version": PDF_EXTRACTOR_VERSION,
        "python_version": PYTHON_VERSION,
        "transformation_id": PDF_TRANSFORMATION_ID,
    }
    if not _strict_equal(runtime, expected_runtime):
        _fail("primary_pdf_runtime_typed_mismatch")

    prior = _exact_mapping(
        row["calendar_xml_prior_expected_unretained"],
        frozenset({"bytes", "sha256", "backfilled", "relabelled", "causal_use"}),
        label="calendar_xml_prior_expected_unretained",
    )
    if not _strict_equal(
        prior,
        {
            "bytes": 12_922,
            "sha256": "e30b070e3db019249bddd3e22e72de504b55466dd23699df873cc3e773d6af91",
            "backfilled": False,
            "relabelled": False,
            "causal_use": "forbidden",
        },
    ):
        _fail("calendar_xml_prior_unretained_contract_mismatch")

    policy = _exact_mapping(
        row["policy"],
        frozenset(
            {
                "registered_with_live_collector",
                "enabled",
                "runtime_supported",
                "research_only",
                "shadow_only",
                "historical_july_availability_counterfactual_only",
                "future_clock_supports_prospective_collection_only",
                "consensus",
                "surprise",
                "direction",
                "proof_eligible",
                "promotion_eligible",
                "authorization_eligible",
                "execution_eligible",
                "supported_execution_decision",
            }
        ),
        label="policy",
    )
    expected_policy = {
        "registered_with_live_collector": False,
        "enabled": False,
        "runtime_supported": False,
        "research_only": True,
        "shadow_only": True,
        "historical_july_availability_counterfactual_only": True,
        "future_clock_supports_prospective_collection_only": True,
        "consensus": None,
        "surprise": None,
        "direction": None,
        "proof_eligible": False,
        "promotion_eligible": False,
        "authorization_eligible": False,
        "execution_eligible": False,
        "supported_execution_decision": "no_trade",
    }
    if not _strict_equal(policy, expected_policy):
        _fail("observation_manifest_policy_typed_mismatch")

    artifacts = row["artifacts"]
    if type(artifacts) is not list or len(artifacts) != len(_ARTIFACT_SPECS):
        _fail("observation_manifest_artifact_count_mismatch")
    by_id: dict[str, dict[str, Any]] = {}
    artifact_fields = frozenset(
        {
            "artifact_id",
            "source_url",
            "final_url",
            "request_started_utc",
            "observed_utc",
            "http_status",
            "http_date",
            "content_type",
            "content_length_header",
            "raw_bytes",
            "raw_sha256",
            "archive_path",
            "role",
            "causal_use",
            "semantic_valid",
            "raw_payload_retained",
            "read_only",
            "pdf_extraction",
        }
    )
    extraction_fields = frozenset(
        {
            "extractor",
            "extractor_version",
            "python_version",
            "transformation_id",
            "page_count",
            "text_archive_path",
            "text_bytes",
            "text_sha256",
            "transformations",
        }
    )
    expected_transformations = [
        "pypdf_page_extract_text_layout",
        "crlf_and_cr_to_lf",
        "rstrip_space_and_tab_per_line",
        "unicode_nfc",
        "strip_each_page",
        "join_pages_with_lf_formfeed_lf",
        "single_terminal_lf",
    ]
    for index, value in enumerate(artifacts):
        artifact = _exact_mapping(value, artifact_fields, label=f"artifact_{index}")
        artifact_id = artifact["artifact_id"]
        if type(artifact_id) is not str or artifact_id in by_id:
            _fail("observation_manifest_artifact_id_invalid_or_duplicate")
        spec = _ARTIFACT_SPECS.get(artifact_id)
        if spec is None:
            _fail("observation_manifest_unknown_artifact")
        expected_values = {
            "artifact_id": artifact_id,
            "source_url": spec["source_url"],
            "final_url": spec["source_url"],
            "http_status": 200,
            "content_type": spec["content_type"],
            "content_length_header": str(spec["bytes"]),
            "raw_bytes": spec["bytes"],
            "raw_sha256": spec["sha256"],
            "archive_path": spec["archive_path"],
            "role": spec["role"],
            "causal_use": spec["causal_use"],
            "semantic_valid": spec["semantic_valid"],
            "raw_payload_retained": True,
            "read_only": True,
        }
        for key, expected in expected_values.items():
            if not _strict_equal(artifact[key], expected):
                _fail(f"observation_manifest_artifact_mismatch:{artifact_id}:{key}")
        requested = _canonical_utc(
            artifact["request_started_utc"], label=f"{artifact_id}_request_started_utc"
        )
        observed = _canonical_utc(
            artifact["observed_utc"], label=f"{artifact_id}_observed_utc"
        )
        http_date = _http_date(artifact["http_date"], label=f"{artifact_id}_http_date")
        if not requested <= observed <= capture_completed:
            _fail(f"observation_manifest_artifact_chronology:{artifact_id}")
        if http_date > observed + dt.timedelta(seconds=2):
            _fail(f"observation_manifest_http_date_future:{artifact_id}")
        if "text_path" in spec:
            extraction = _exact_mapping(
                artifact["pdf_extraction"], extraction_fields, label=f"{artifact_id}_extraction"
            )
            expected_extraction = {
                "extractor": PDF_EXTRACTOR,
                "extractor_version": PDF_EXTRACTOR_VERSION,
                "python_version": PYTHON_VERSION,
                "transformation_id": PDF_TRANSFORMATION_ID,
                "page_count": spec["page_count"],
                "text_archive_path": spec["text_path"],
                "text_bytes": spec["text_bytes"],
                "text_sha256": spec["text_sha256"],
                "transformations": expected_transformations,
            }
            if not _strict_equal(extraction, expected_extraction):
                _fail(f"observation_manifest_extraction_mismatch:{artifact_id}")
        elif artifact["pdf_extraction"] is not None:
            _fail(f"observation_manifest_unexpected_pdf_extraction:{artifact_id}")
        by_id[artifact_id] = artifact
    if set(by_id) != set(_ARTIFACT_SPECS):
        _fail("observation_manifest_artifact_membership_mismatch")
    return row


def load_observation_manifest() -> dict[str, Any]:
    path = _workspace_path(OBSERVATION_MANIFEST_PATH)
    raw = _read_exact_pinned_file(
        path,
        expected_path=path,
        expected_bytes=OBSERVATION_MANIFEST_BYTES,
        expected_sha256=OBSERVATION_MANIFEST_SHA256,
    )
    return _validate_observation_manifest(_strict_json(raw, label="observation_manifest"))


def _artifact_map(manifest: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    return {row["artifact_id"]: row for row in manifest["artifacts"]}


def _read_artifact(artifact_id: str) -> bytes:
    spec = _ARTIFACT_SPECS[artifact_id]
    path = _workspace_path(spec["archive_path"])
    return _read_exact_pinned_file(
        path,
        expected_path=path,
        expected_bytes=spec["bytes"],
        expected_sha256=spec["sha256"],
    )


def _read_and_verify_pdf_text(artifact_id: str) -> str:
    spec = _ARTIFACT_SPECS[artifact_id]
    raw = _read_artifact(artifact_id)
    extracted, page_count = _normalized_pdf_text(raw)
    if page_count != spec["page_count"]:
        _fail(f"pdf_page_count_mismatch:{artifact_id}")
    if len(extracted) != spec["text_bytes"]:
        _fail(f"pdf_text_byte_count_mismatch:{artifact_id}")
    if hashlib.sha256(extracted).hexdigest() != spec["text_sha256"]:
        _fail(f"pdf_text_sha256_mismatch:{artifact_id}")
    text_path = _workspace_path(spec["text_path"])
    retained = _read_exact_pinned_file(
        text_path,
        expected_path=text_path,
        expected_bytes=spec["text_bytes"],
        expected_sha256=spec["text_sha256"],
    )
    if retained != extracted:
        _fail(f"pdf_retained_text_not_reproducible:{artifact_id}")
    return extracted.decode("utf-8")


def _scheduled_utc(event_date: str) -> dt.datetime:
    local = dt.datetime.fromisoformat(f"{event_date}T06:00:00").replace(
        tzinfo=ZoneInfo(TIMEZONE_NAME)
    )
    if local.utcoffset() != dt.timedelta(hours=-6) or local.dst() != dt.timedelta(0):
        _fail("mexico_city_2026_timezone_contract_failed")
    return local.astimezone(UTC)


def _iso_z(value: dt.datetime) -> str:
    return value.astimezone(UTC).isoformat().replace("+00:00", "Z")


def _event_id(event_date: str) -> str:
    return f"mxn_inegi_cpi_release:{event_date}"


def _episode_key(event_date: str) -> str:
    return f"MXN:inegi_cpi_release:{event_date}"


def _guardrails() -> dict[str, Any]:
    return dict(_GUARDRAILS)


def _assert_guardrails(value: Mapping[str, Any]) -> None:
    for key, expected in _GUARDRAILS.items():
        if not _strict_equal(value.get(key), expected):
            _fail(f"guardrail_violation:{key}")
    forbidden = {
        "expected_net_pips",
        "forecast_mean_bps",
        "allocator_rank",
        "trade_side",
        "signal_direction",
        "raw_pdf",
        "raw_xml",
        "full_text",
    }
    overlap = forbidden.intersection(value)
    if overlap:
        _fail(f"forbidden_output_surface:{','.join(sorted(overlap))}")


def _parse_calendar(manifest: Mapping[str, Any]) -> list[dict[str, Any]]:
    text = _read_and_verify_pdf_text("calendar_pdf")
    pages = text.split("\n\f\n")
    target_pages = [
        page
        for page in pages
        if "Índice Nacional de Precios al Consumidor, 2.ª quincena y mensual." in page
    ]
    if len(target_pages) != 1:
        _fail("calendar_target_section_missing_or_ambiguous")
    page = re.sub(r"\s+", " ", target_pages[0])
    if "la información se difunde a las 06:00 a.m." not in page:
        _fail("calendar_release_time_missing")
    target_heading = "Índice Nacional de Precios al Consumidor, 2.ª quincena y mensual."
    next_heading = "Índice Nacional de Precios Productor (INPP)"
    start = page.find(target_heading)
    end = page.find(next_heading, start + len(target_heading))
    if start < 0 or end <= start:
        _fail("calendar_target_section_boundary_missing")
    target_section = page[start:end]
    pairs = (("07/agosto", "Julio"), ("09/septiembre", "Agosto"))
    for date_label, period_label in pairs:
        if len(
            re.findall(
                rf"\b{re.escape(date_label)}\s+{period_label}\b", target_section
            )
        ) != 1:
            _fail(f"calendar_date_period_missing_or_ambiguous:{date_label}")

    artifacts = _artifact_map(manifest)
    observed_text = artifacts["calendar_pdf"]["observed_utc"]
    observed = _canonical_utc(observed_text, label="calendar_pdf_observed_utc")
    rows: list[dict[str, Any]] = []
    for expected in EXPECTED_CLOCKS:
        scheduled = _scheduled_utc(expected["event_date"])
        if _iso_z(scheduled) != expected["scheduled_utc"]:
            _fail("calendar_utc_derivation_mismatch")
        captured_pre_event = observed < scheduled
        historical = expected["event_date"] == "2026-08-07"
        prospective_schedule = not historical and captured_pre_event
        collection_class = (
            "historical_availability_counterfactual_archive_only"
            if historical
            else "prospective_schedule_only"
            if captured_pre_event
            else "late_schedule_capture_archive_only"
        )
        if collection_class != expected["collection_class"]:
            _fail("calendar_collection_class_mismatch")
        row = {
            "schema_version": SCHEMA_VERSION,
            "source_id": SOURCE_ID,
            "source_contract_id": CONTRACT_ID,
            "source_cohort_id": COHORT_ID,
            "event_id": _event_id(expected["event_date"]),
            "event_series_id": "mxn_inegi_cpi_release",
            "event_date": expected["event_date"],
            "reference_period": expected["reference_period"],
            "currency": "MXN",
            "currency_factor": "MXN",
            "independent_episode_key": _episode_key(expected["event_date"]),
            "local_timezone": TIMEZONE_NAME,
            "local_time": expected["local_time"],
            "scheduled_utc": expected["scheduled_utc"],
            "calendar_observed_utc": observed_text,
            "calendar_captured_pre_event": captured_pre_event,
            "prospective_schedule": prospective_schedule,
            "collection_class": collection_class,
            "calendar_source_url": CALENDAR_PDF_URL,
            "calendar_source_sha256": _ARTIFACT_SPECS["calendar_pdf"]["sha256"],
            "calendar_source_bytes": _ARTIFACT_SPECS["calendar_pdf"]["bytes"],
            "calendar_text_sha256": _ARTIFACT_SPECS["calendar_pdf"]["text_sha256"],
            "calendar_xml_used": False,
            "calendar_xml_prior_snapshot_backfilled": False,
            **_guardrails(),
        }
        _assert_guardrails(row)
        rows.append(row)
    return rows


def _parse_decimal(value: str, *, label: str) -> Decimal:
    try:
        parsed = Decimal(value)
    except InvalidOperation as exc:
        raise MxnInegiCpiExactSourceError(f"{label}_invalid_decimal") from exc
    if not parsed.is_finite():
        _fail(f"{label}_nonfinite")
    return parsed


def _parse_xml_fact(artifact_id: str) -> tuple[str, Decimal]:
    spec = _ARTIFACT_SPECS[artifact_id]
    raw = _read_artifact(artifact_id)
    try:
        root = ET.fromstring(raw)
    except ET.ParseError as exc:
        raise MxnInegiCpiExactSourceError(f"xml_parse_failed:{artifact_id}") from exc
    if root.tag != "DATASET" or root.attrib or len(root) != 2:
        _fail(f"xml_root_contract_mismatch:{artifact_id}")
    metadata, series = root
    if metadata.tag != "METADATA" or metadata.attrib:
        _fail(f"xml_metadata_contract_mismatch:{artifact_id}")
    if series.tag != "SERIE" or series.attrib or len(series) != 1:
        _fail(f"xml_series_contract_mismatch:{artifact_id}")
    expected_tags = [
        "Nemonic",
        "Name",
        "Name",
        "Unit",
        "Unit",
        "Freq",
        "Freq",
        "NoOfDecimals",
        "LastUpdate",
        "CreationDate",
    ]
    if [child.tag for child in metadata] != expected_tags:
        _fail(f"xml_metadata_membership_mismatch:{artifact_id}")
    values = {child.tag: (child.text or "").strip() for child in metadata if child.tag not in {"Name", "Unit", "Freq"}}
    if values != {
        "Nemonic": spec["nemonic"],
        "NoOfDecimals": "3",
        "LastUpdate": "07/08/2026",
        "CreationDate": "07/08/2026",
    }:
        _fail(f"xml_metadata_value_mismatch:{artifact_id}")
    for child in metadata:
        if child.tag in {"Name", "Unit", "Freq"}:
            if set(child.attrib) != {"{http://www.w3.org/XML/1998/namespace}lang"}:
                _fail(f"xml_language_attribute_mismatch:{artifact_id}")
            if child.attrib["{http://www.w3.org/XML/1998/namespace}lang"] not in {"en", "es"}:
                _fail(f"xml_language_value_mismatch:{artifact_id}")
        elif child.attrib:
            _fail(f"xml_unexpected_metadata_attribute:{artifact_id}")
    obs = series[0]
    if obs.tag != "Obs" or len(obs) != 0 or set(obs.attrib) != {"TimePeriod", "CurrentValue"}:
        _fail(f"xml_observation_contract_mismatch:{artifact_id}")
    if (obs.text or "").strip() or obs.tail and obs.tail.strip():
        _fail(f"xml_observation_text_forbidden:{artifact_id}")
    if obs.attrib["TimePeriod"] != "2026/07":
        _fail(f"xml_reference_period_mismatch:{artifact_id}")
    parsed_raw = _parse_decimal(obs.attrib["CurrentValue"], label=artifact_id)
    # INEGI declares three decimals but serializes binary-float tails in the
    # current-value attribute.  Normalize only to that explicit source
    # precision; retain the raw bytes and never round beyond the declared unit.
    parsed = parsed_raw.quantize(Decimal("0.001"))
    expected = EXPECTED_JULY_FACTS[spec["fact_name"]]
    if parsed != expected.quantize(Decimal("0.001")):
        _fail(f"xml_fact_value_mismatch:{artifact_id}")
    return spec["fact_name"], expected


def _extract_unique_decimal(text: str, pattern: str, *, label: str) -> Decimal:
    matches = re.findall(pattern, text, flags=re.IGNORECASE)
    if len(matches) != 1:
        _fail(f"pdf_fact_missing_or_ambiguous:{label}")
    return _parse_decimal(matches[0], label=label)


def _parse_release_pdf_facts() -> dict[str, Decimal]:
    text = _read_and_verify_pdf_text("july_release_pdf")
    collapsed = re.sub(r"\s+", " ", text)
    if len(re.findall(r"7 de agosto de 2026", collapsed, flags=re.IGNORECASE)) != 6:
        _fail("release_pdf_date_or_page_count_mismatch")
    if "ÍNDICE NACIONAL DE PRECIOS AL CONSUMIDOR (INPC)" not in collapsed.upper():
        _fail("release_pdf_title_missing")
    facts = {
        "headline_monthly_pct": _extract_unique_decimal(
            collapsed,
            r"aumentó\s+([0-9]+(?:\.[0-9]+)?)\s*%\s+respecto al mes anterior",
            label="headline_monthly_pct",
        ),
        "headline_annual_pct": _extract_unique_decimal(
            collapsed,
            r"inflación general anual se ubicó en\s+([0-9]+(?:\.[0-9]+)?)\s+por ciento",
            label="headline_annual_pct",
        ),
        "core_monthly_pct": _extract_unique_decimal(
            collapsed,
            r"índice de precios subyacente.*?creció\s+([0-9]+(?:\.[0-9]+)?)\s*%\s+a tasa mensual",
            label="core_monthly_pct",
        ),
        "core_annual_pct": _extract_unique_decimal(
            collapsed,
            r"A tasa anual,\s+en\s+julio pasado,\s+los\s+índices\s+subyacente\s+y\s+no subyacente\s+ascendieron\s+([0-9]+(?:\.[0-9]+)?)\s+y",
            label="core_annual_pct",
        ),
    }
    if facts != EXPECTED_JULY_FACTS:
        _fail("release_pdf_fact_bundle_mismatch")
    return facts


def _parse_july_release(
    manifest: Mapping[str, Any], calendar: list[dict[str, Any]]
) -> dict[str, Any]:
    calendar_rows = [row for row in calendar if row["event_date"] == "2026-08-07"]
    if len(calendar_rows) != 1:
        _fail("july_calendar_event_not_unique")
    calendar_event = calendar_rows[0]
    pdf_facts = _parse_release_pdf_facts()
    xml_facts: dict[str, Decimal] = {}
    for artifact_id in (
        "headline_annual_xml",
        "headline_monthly_xml",
        "core_annual_xml",
        "core_monthly_xml",
    ):
        name, value = _parse_xml_fact(artifact_id)
        if name in xml_facts:
            _fail("duplicate_xml_fact")
        xml_facts[name] = value
    if xml_facts != pdf_facts or xml_facts != EXPECTED_JULY_FACTS:
        _fail("pdf_xml_corroboration_mismatch")

    artifacts = _artifact_map(manifest)
    fact_observations = [
        _canonical_utc(artifacts[artifact_id]["observed_utc"], label=f"{artifact_id}_observed")
        for artifact_id in (
            "july_release_pdf",
            "headline_annual_xml",
            "headline_monthly_xml",
            "core_annual_xml",
            "core_monthly_xml",
        )
    ]
    known = max(fact_observations)
    scheduled = dt.datetime.fromisoformat(
        calendar_event["scheduled_utc"].replace("Z", "+00:00")
    )
    if known <= scheduled:
        _fail("historical_july_knowledge_time_not_after_release")
    facts_serialized = {key: str(value) for key, value in EXPECTED_JULY_FACTS.items()}
    record = {
        "schema_version": SCHEMA_VERSION,
        "source_id": SOURCE_ID,
        "source_contract_id": CONTRACT_ID,
        "source_cohort_id": COHORT_ID,
        "event_id": _event_id("2026-08-07"),
        "event_series_id": "mxn_inegi_cpi_release",
        "event_date": "2026-08-07",
        "reference_period": "2026-07",
        "currency": "MXN",
        "currency_factor": "MXN",
        "independent_episode_key": _episode_key("2026-08-07"),
        "scheduled_utc": calendar_event["scheduled_utc"],
        "fact_bundle_known_utc": known.isoformat(),
        "collection_class": "historical_availability_counterfactual_archive_only",
        "historical_availability_counterfactual": True,
        "prospective_observation": False,
        "facts": facts_serialized,
        "facts_sha256": canonical_sha256(facts_serialized),
        "pdf_xml_corroborated": True,
        "calendar_source_sha256": _ARTIFACT_SPECS["calendar_pdf"]["sha256"],
        "release_pdf_sha256": _ARTIFACT_SPECS["july_release_pdf"]["sha256"],
        "release_pdf_text_sha256": _ARTIFACT_SPECS["july_release_pdf"]["text_sha256"],
        "xml_source_sha256": {
            artifact_id: _ARTIFACT_SPECS[artifact_id]["sha256"]
            for artifact_id in (
                "headline_annual_xml",
                "headline_monthly_xml",
                "core_annual_xml",
                "core_monthly_xml",
            )
        },
        "calendar_xml_used": False,
        "calendar_xml_later_revision_quarantined": True,
        **_guardrails(),
    }
    _assert_guardrails(record)
    return record


def load_exact_inegi_cpi_snapshot() -> dict[str, Any]:
    manifest = load_observation_manifest()
    # Reopen the quarantined response too.  Its exact bytes prove the drift but
    # its semantic-invalid status prevents it from contributing any clock.
    quarantined = _read_artifact("calendar_xml_later_revision")
    if b"P\xc3\xa1gina no encontrada" not in quarantined and b"Esta liga ya no existe" not in quarantined:
        _fail("calendar_xml_quarantine_content_not_recognized")
    calendar = _parse_calendar(manifest)
    july = _parse_july_release(manifest, calendar)
    output = {
        "schema_version": SCHEMA_VERSION,
        "source_id": SOURCE_ID,
        "source_contract_id": CONTRACT_ID,
        "source_cohort_id": COHORT_ID,
        "observation_manifest_path": OBSERVATION_MANIFEST_PATH,
        "observation_manifest_sha256": OBSERVATION_MANIFEST_SHA256,
        "calendar_authority": "calendar_pdf",
        "calendar_events": calendar,
        "historical_july_release": july,
        "calendar_xml_later_revision": {
            "observed_utc": _artifact_map(manifest)["calendar_xml_later_revision"]["observed_utc"],
            "bytes": _ARTIFACT_SPECS["calendar_xml_later_revision"]["bytes"],
            "sha256": _ARTIFACT_SPECS["calendar_xml_later_revision"]["sha256"],
            "semantic_valid": False,
            "causal_use": "forbidden_for_prior_clock_or_proof",
            "prior_expected_snapshot_retained": False,
            "prior_expected_snapshot_backfilled": False,
            "prior_expected_snapshot_relabelled": False,
        },
        "optional_historical_xmls_retained": False,
        **_guardrails(),
    }
    _assert_guardrails(output)
    output["snapshot_id"] = "mxn_inegi_cpi_exact_v1_snapshot_" + canonical_sha256(output)[:24]
    return output


EXPECTED_CONTRACT_MANIFEST: dict[str, Any] = {
    "schema_version": 1,
    "source_id": SOURCE_ID,
    "source_contract_id": CONTRACT_ID,
    "source_cohort_id": COHORT_ID,
    "registered_with_live_collector": False,
    "enabled": False,
    "runtime_supported": False,
    "research_only": True,
    "shadow_only": True,
    "currency": "MXN",
    "currency_factor": "MXN",
    "timezone": TIMEZONE_NAME,
    "timezone_contract": "UTC-06:00 for the two accepted 2026 clocks; DST forbidden",
    "calendar_authority": "calendar_pdf",
    "observation_manifest_path": OBSERVATION_MANIFEST_PATH,
    "observation_manifest_bytes": OBSERVATION_MANIFEST_BYTES,
    "observation_manifest_sha256": OBSERVATION_MANIFEST_SHA256,
    "pdf_extractor": PDF_EXTRACTOR,
    "pdf_extractor_version": PDF_EXTRACTOR_VERSION,
    "python_pdf_runtime_version": PYTHON_VERSION,
    "pdf_transformation_id": PDF_TRANSFORMATION_ID,
    "accepted_clocks": EXPECTED_CLOCKS,
    "july_facts": {key: str(value) for key, value in EXPECTED_JULY_FACTS.items()},
    "artifacts": {
        artifact_id: {
            "source_url": spec["source_url"],
            "archive_path": spec["archive_path"],
            "bytes": spec["bytes"],
            "sha256": spec["sha256"],
            "role": spec["role"],
            "causal_use": spec["causal_use"],
            "semantic_valid": spec["semantic_valid"],
        }
        for artifact_id, spec in _ARTIFACT_SPECS.items()
    },
    "prior_calendar_xml": {
        "expected_bytes": 12_922,
        "expected_sha256": "e30b070e3db019249bddd3e22e72de504b55466dd23699df873cc3e773d6af91",
        "retained": False,
        "backfilled": False,
        "relabelled": False,
        "causal_use": "forbidden",
    },
    "optional_historical_xmls_retained": False,
    "hard_guards": {
        "consensus": None,
        "surprise": None,
        "direction": None,
        "currency_bias": None,
        "pair_bias": None,
        "confirmation_eligible": False,
        "proof_eligible": False,
        "promotion_eligible": False,
        "authorization_eligible": False,
        "execution_eligible": False,
        "can_authorize": False,
        "can_place_orders": False,
        "supported_execution_decision": "no_trade",
    },
    "separation_contract": {
        "existing_banxico_source_untouched": True,
        "touch_live_news_config": False,
        "touch_live_collector": False,
        "touch_immutable_event_clock": False,
        "touch_database": False,
        "touch_executor_or_account": False,
        "write_process_state": False,
    },
}


def load_contract_manifest(path: str | Path) -> dict[str, Any]:
    raw = Path(path).read_bytes()
    manifest = _strict_json(raw, label="contract_manifest")
    if not _strict_equal(manifest, EXPECTED_CONTRACT_MANIFEST):
        _fail("contract_manifest_deep_typed_mismatch")
    load_observation_manifest()
    return manifest


__all__ = [
    "CALENDAR_PDF_URL",
    "COHORT_ID",
    "CONTRACT_ID",
    "EXPECTED_CLOCKS",
    "EXPECTED_JULY_FACTS",
    "JULY_RELEASE_PDF_URL",
    "MxnInegiCpiExactSourceError",
    "OBSERVATION_MANIFEST_BYTES",
    "OBSERVATION_MANIFEST_PATH",
    "OBSERVATION_MANIFEST_SHA256",
    "PDF_EXTRACTOR_VERSION",
    "PDF_TRANSFORMATION_ID",
    "SCHEMA_VERSION",
    "SOURCE_ID",
    "TIMEZONE_NAME",
    "canonical_sha256",
    "load_contract_manifest",
    "load_exact_inegi_cpi_snapshot",
    "load_observation_manifest",
]
