from pathlib import Path
import json,hashlib,datetime,difflib,re
B=Path(r'C:\Users\zmoor\Documents\forex\overnight_curve_buildout_20260909'); P=B.parent/'trad'; D=B/'documentation_final_draft_001'; O=B/'documentation_early_close_final_001'; O.mkdir(exist_ok=False)
receipt=json.loads((D/'DOCUMENTATION_DRAFT_20260909.json').read_bytes()); files={Path(r['path']).name:Path(r['path']) for r in receipt['records']}; before={n:p.read_bytes() for n,p in files.items()}
for r in receipt['records']: assert hashlib.sha256(Path(r['path']).read_bytes()).hexdigest()==r['sha256']
texts={n:b.decode('utf-8') for n,b in before.items()}
def sub(n,a,b):
 assert texts[n].count(a)==1,(n,a[:80]);texts[n]=texts[n].replace(a,b)
r='FOREX_OVERNIGHT_CURVE_BUILDOUT_20260909.md'
sub(r,'Draft finalization at 12:10 UTC / 08:10 Eastern. This report distinguishes completed engineering and dated observations from the final main-study, pilot, risk and runtime checks still due before the 13:00 UTC handoff.','Closeout requested at approximately 12:08 UTC / 08:08 Eastern. This report uses the latest completed, dated assessments. The planned later main/pilot/risk evaluations were canceled before starting. Existing observation/collection processes retain their original limits through 12:45–13:00 UTC; their remaining data is not claimed evaluated here.')
sub(r,'The final main-study snapshot is still pending.','The planned 12:15 reassessment did not run; this remains the latest completed main-study assessment.')
sub(r,'The final pilot pass is still pending.','The planned later evaluation did not run; pending original targets and missing observations remain explicit at this cutoff.')
sub(r,'Final retained outcomes are still pending.','The latest completed audit at 10:17:59–10:19:53 UTC verified 68 original chains and 372 sources with zero audit issues, retaining all 216 groups and 108 paired-method cells. At 15/30/60 minutes, scored/pending node counts were 1,416/216, 1,248/384 and 888/744; these are overlapping node counts, not independent N. Scheduled dispositions were 68 verified, seven withheld/partial and 51 not yet started at that cutoff. The later evaluation was canceled before starting. [Complete dated risk results](validation/overnight_curve_buildout_20260909/richer_inputs/prospective_risk_v1/complete_results_004/COMPLETE_RETAINED_RISK_RESULTS_20260909.json).')
sub(r,'The final news/runtime check is pending; that older sample is not current telemetry.','The longer news observation was not completed for this closeout; that older sample is not current telemetry.')
sub(r,'TRY/JPY and USD/TRY are registered, activated models with no publications in the dated 10:34 audit. Their last original readiness-log samples had 17 and 40 mature exact-H1 joint rows against 48 required, observed at 10:22:09 and 10:26:05. Later quotes were tradeable. These are retained attempt/readiness facts, not recomputed current progress; the minimum was not relaxed. Persisting pre-attempt refusals remains useful future work.','TRY/JPY and USD/TRY are registered, activated models without accepted current forecasts. The latest retained family-readiness samples remained blocked: TRY/JPY had 17 of 48 required mature exact-H1 joint rows at 11:59:48.059 UTC, and USD/TRY had 37 of 48 at 12:06:32.901. USD/TRY previously had 40: these windowed counts are not monotonic progress or an ETA. A top-level price-ready label does not override blocked model-family readiness. These are original logged facts, not a recomputed fit; the minimum was not relaxed. [Readiness refresh](validation/overnight_curve_buildout_20260909/try_pair_publication_audit_v1/TRY_READINESS_REFRESH_001_20260909.json).')
sub(r,'The 09:40 audit found 15 expected main workers; the paper process later completed naturally. Final current process/news/source checks remain pending. Thirteen old producer errors and five historical news-clock errors were observed previously; missing original failure inputs prevent causal attribution from later recovery.','The closeout read at 12:09:03.169–12:09:09.993 UTC verified all 15 main workers, 35 project processes, all four frozen source closures and 66 current forecasts. The original producer envelope still had a generation mismatch and 13 recorded errors. Repaired-news output was current while its cumulative error count remained five and last_error was null; that does not recover missing original failure evidence. Only 67 of 68 quotes were within 60 seconds. Archive last-complete price ages ranged 185.66–365.65 seconds, based on retained tail clocks. The latest logical news capture measured 14,084,557 of 16,777,216 bytes; this was a byte/hash capacity check, not semantic seal replay. Process liveness and independent forecast availability do not establish complete upstream correctness. [Closeout operations](validation/overnight_curve_buildout_20260909/operations_v3/OPERATIONS_V3_OBSERVATION_004_20260909.json).')
sub(r,'The portable validation will embed copied-member hashes, current source dependencies and all four frozen closures.','The initial portable project copy retained 617 selected files (26,554,108 bytes); the final validation/publication receipt will identify the exact final copied members, source dependencies and four frozen closures.')
sub(r,'Remaining work: complete final main/pilot/risk/runtime checks and publication; register a genuinely shared issue grid and fresh-update management comparison; obtain independent sessions for magnitude, after-cost and calibration acceptance; preserve future refusal/clock evidence and monitor capacity. No execution or promotion is authorized. The final source/record publication receipts, not this draft, will establish what reached the vault.','Remaining research: evaluate later retained outcomes in a separate authorized pass; register a genuinely shared issue grid and fresh-update management comparison; obtain independent sessions for magnitude, after-cost and calibration acceptance; preserve future refusal/clock evidence and monitor capacity. The user requested closeout before the original 13:00 UTC work deadline. No execution or promotion is authorized. Final source/record publication is a separate step: its receipts establish what reached the vault, and this report does not claim it already succeeded.')
p='FOREX_PENDING_IMPROVEMENTS.md'
sub(p,'## Current — September 9 finalization, draft 12:10 UTC','## Current — September 9 early closeout, requested about 12:08 UTC')
sub(p,'final observations still pending before 13:00 UTC','unevaluated later observations after the user requested an early close')
sub(p,'1. Finish final main, pilot, risk, runtime/news/source verification and portable evidence publication; preserve missing and pending outcomes explicitly.','1. Finish the separate source/evidence publication receipt. Planned later main/pilot/risk evaluations were canceled before starting; any later retained outcomes need a separate authorized assessment, preserving missing/pending denominators. Existing collection/observation processes retain their original end limits.')
sub(p,'Current V2 observation: 19 fresh retry recoveries, zero final failures, 66 forecasts on every poll.','Completed V2 probe: 19 fresh retry recoveries, zero final failures, 66 forecasts on every poll. The 12:09 operations read verified 15 main workers, 35 processes, four source closures and 66 current forecasts, while the original producer mismatch/errors and one quote older than 60 seconds remained visible.')
rd='README.md';sub(rd,'Final observations/publication remain pending in the 12:10 UTC draft.','The user requested closeout around 12:08 UTC; later evaluations were canceled before starting. The report uses completed dated results and the 12:09 operations read. Source/record publication has its own completion receipt.')
g='FOREX_AUDIT_START_HERE.md';sub(g,'The 12:10 UTC narrative is a finalization draft: later outcome/runtime checks and final publication are still pending.','The narrative closes at the user\'s request around 12:08 UTC, using completed dated results and the 12:09 operations read. Later outcome evaluations were canceled before starting; remaining collection windows are not completed assessments. Publication succeeds only when the separate validation/source receipts say so.')
l='FOREX_PROJECT_LOG.md'; cut=texts[l].index('\n## 2026-09-09 12:10 UTC — completed engineering; final observations still pending');texts[l]=texts[l][:cut]
now=datetime.datetime.now(datetime.timezone.utc); stamp=now.strftime('%Y-%m-%d %H:%M UTC')
texts[l]+=f'''\n## {stamp} — user-requested early closeout; later evaluations not run\n\nThe user requested closeout at approximately 12:08 UTC, before the original 13:00 work deadline. This entry records the actual documentation completion time. The draft was written at 12:05:06 UTC with an intended 12:10 heading; its exact bytes are retained in documentation_final_draft_001 and are superseded here. Original earlier log history is unchanged.\n\nLatest completed results remain joint assessment001 (2,182 original outcomes, negative after spread), fixed probability analysis002 (68 tests; original Brier 0.2521189983 and 13 flats), pilot complete table002 (1,154 chains; 27,964 scored node views with pending/missing counts retained), risk004 (68 chains,216 groups/108 paired cells), and all three paper episodes (curve net -$5.67382004780 versus hold +$2.05980878530). The planned later main/pilot/risk evaluations were canceled before starting. Existing collection/news-observation processes retain their original limits; remaining observations are not claimed evaluated.\n\nThe final 12:09:03–12:09:09 operations read verified 15 main workers,35 processes,all four frozen closures and66 current forecasts. Original producer generation mismatch/13 errors and repaired-news cumulative five errors remain explicit;67/68 quotes were within60 seconds. Logged TRY family readiness was17/48 and37/48 at separate original clocks, not a monotonic ETA.\n\nCompleted engineering includes the V2 endpoint probe (77 polls/67 reports,19 first failures and19 fresh forecast recoveries,zero final failures); inactive existing-manager reconciliation86 tests; channels39; bridge315 overlapping integration cases; and dictionary metadata build/check34 tests. These test counts are not additive. The H3 bridge used an old issued chain,a newly observed quote and hypothetical flat state; it was not a fresh forecast or fill. The Sep8 dictionary validation remains historical; the Sep9 metadata receipt binds refreshed documents without feature-math changes.\n\nOnly the five assigned documentation files changed in this closeout. Prior bytes/diffs/hashes are retained. Initial portable project copy001 completed with617 files/26,554,108 bytes; final validation and vault publication remain separate receipt-bound actions. No model,scorer,registry,runtime,execution authorization or publisher mapping changed in this documentation pass.\n'''
records=[]
for n,p in files.items():
 raw=texts[n].encode('utf-8'); old=before[n];(O/(n+'.before')).write_bytes(old);p.write_bytes(raw);assert p.read_bytes()==raw;(O/n).write_bytes(raw)
 (O/(n+'.diff.txt')).write_text(''.join(difflib.unified_diff(old.decode().splitlines(True),texts[n].splitlines(True),fromfile=n+' draft001',tofile=n+' early-close-final')),encoding='utf-8')
 records.append({'path':str(p),'sha256':hashlib.sha256(raw).hexdigest(),'bytes':len(raw),'before_sha256':hashlib.sha256(old).hexdigest()})
original_log=(B/'documentation_before_final_001'/l).read_bytes();assert files[l].read_bytes().startswith(original_log)
pending_original=(B/'documentation_before_final_001'/p if False else B/'documentation_before_final_001'/'FOREX_PENDING_IMPROVEMENTS.md').read_bytes().decode();assert pending_original.split('\n',1)[1].strip() in texts['FOREX_PENDING_IMPROVEMENTS.md']
v={'status':'documentation_frozen_for_early_closeout','created_utc':now.isoformat(),'user_close_request_approx_utc':'2026-09-09T12:08:00Z','records':records,'original_log_prefix_preserved':True,'old_pending_history_preserved':True,'runtime_changes':False,'publication_claim':'separate receipt required','later_main_pilot_risk_evaluations':'canceled before start'}
f=O/'DOCUMENTATION_EARLY_CLOSE_FINAL_20260909.json';f.write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8');print(json.dumps({'receipt':str(f),'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'records':records}))