"""Apply the reviewed overview layout only; no process or runtime access."""
from pathlib import Path

path = Path(__file__).resolve().parents[1]/'trad/oanda_main_signal_dashboard.html'
text = path.read_text(encoding='utf-8')


def replace(old, new):
    global text
    assert text.count(old) == 1, old[:100]
    text = text.replace(old, new)


replace('    .dot.collection{background:var(--blue)}', '''    .dot.collection{background:var(--blue)}
    .overview-columns{display:grid;grid-template-columns:1fr 1fr;gap:24px}.overview-columns h3{font-size:14px;margin:0 0 8px}.overview-note{font-size:12px;color:var(--muted);margin:8px 0}.bot-summary{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap}.bot-summary strong{font-size:16px}.bot-tags{display:flex;gap:8px;flex-wrap:wrap}.collection-progress{height:6px;max-width:420px;background:var(--line);border-radius:4px;overflow:hidden;margin:8px 0}.collection-progress span{display:block;height:100%;background:var(--blue)}.compact-details{margin-top:10px;font-size:12px}.compact-details summary{cursor:pointer;color:var(--muted)}.compact-details .detail-body{padding:10px 0;line-height:1.7;overflow-wrap:anywhere}.market-table td,.market-table th{padding:10px 12px}.market-table td:not(:first-child),.market-table th:not(:first-child){text-align:right}.context-row{padding:9px 0;border-bottom:1px solid var(--line)}.account-summary{display:flex;gap:24px;flex-wrap:wrap;padding:10px 0}.account-summary strong{font-size:17px}.dot.blocked{background:var(--amber)}
    @media(max-width:680px){.overview-columns{grid-template-columns:1fr;gap:20px}.market-table .optional-column{display:none}.market-table td,.market-table th{padding:9px 6px}.bot-summary strong{font-size:15px}}''')
replace('<h1>Trading Operations</h1>', '<h1>Forex overview</h1>')
replace('<section id="collection-status" aria-live="polite"></section><section id="account"></section><section id="top"></section><section id="live-movers"><div class="empty">Loading executable move census.</div></section>',
        '<section id="market-overview"><div class="empty">Loading current market prices.</div></section><section id="available-signals"></section><section id="collection-status" aria-live="polite"></section><section id="account"></section>')
replace('data-state-key="oanda-evidence-proof"><summary><div><h2>Evidence &amp; proof</h2><div class="subvalue">Live forecast inputs, matured outcomes, and observation-only cohorts</div>',
        'data-state-key="forex-history-v3"><summary><div><h2>Historical observations &amp; research</h2><div class="subvalue">Saved move census, prior forecasts and audit evidence — dated separately from the live overview</div>')
replace('<div class="dashboard-deep-body"><section id="signal-matrix">',
        '<div class="dashboard-deep-body"><section id="live-movers"></section><section id="top"></section><section id="signal-matrix">')
replace('data-state-key="oanda-deep-research"', 'data-state-key="forex-diagnostics-v3"')
start = text.index('    function renderAccount(data)')
end = text.index('    function renderNarrativeMeter(data)', start)
text = text[:start] + '''    function renderAccount(data){
      const a=data.account||{},verified=Date.parse(a.verified_at_utc||''),age=(Date.now()-verified)/1000,fresh=Number.isFinite(age)&&age>=0&&age<=90;
      const valuesCurrent=fresh&&a.account_values_current===true,positionsCurrent=fresh&&a.positions_current===true,ordersCurrent=fresh&&a.orders_current===true,positions=positionsCurrent&&Array.isArray(a.positions)?a.positions:[];
      const money=value=>value==null?'—':`$${num(value,2)}`;
      $('account').innerHTML=`<div class="section-head"><h2>Positions</h2><span class="muted">Practice account ${esc(a.suffix||'-007')} · ${fresh?`${num(age,0)}s since broker verification`:'Current broker state unavailable'}</span></div><div class="account-summary"><div><span class="label">Account value</span><strong>${valuesCurrent?money(a.nav):'—'}</strong></div><div><span class="label">Open P/L</span><strong class="${valuesCurrent?cls(a.unrealized_pl):''}">${valuesCurrent?money(a.unrealized_pl):'—'}</strong></div><div><span class="label">Pending orders</span><strong>${ordersCurrent&&a.pending_orders!=null?Number(a.pending_orders):'—'}</strong></div></div>${!positionsCurrent?'<div class="empty">Position/order state unavailable — not confirmed flat.</div>':positions.length?`<div class="table-wrap"><table><thead><tr><th>Pair</th><th>Side</th><th>Units</th><th>Entry</th><th>Open P/L</th><th>Protection</th></tr></thead><tbody>${positions.map(p=>`<tr><td><strong>${esc(p.instrument)}</strong></td><td>${esc(p.direction||'')}</td><td>${num(p.units,0)}</td><td>${num(p.entry_price,String(p.instrument).endsWith('_JPY')?3:5)}</td><td class="${cls(p.unrealized_pl)}">${money(p.unrealized_pl)}</td><td>${ordersCurrent?esc((p.protection||[]).join(', ')||'none'):'Order state unavailable'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No open positions.</div>'}<details class="compact-details" data-state-key="account-receipt-v3"><summary>Account details</summary><div class="detail-body">Balance: ${valuesCurrent?money(a.balance):'unavailable'} · Realized P/L: ${valuesCurrent?money(a.realized_pl):'unavailable'} · Margin used: ${valuesCurrent?money(a.margin_used):'unavailable'}<br>Broker verification: ${esc(a.verified_at_utc||'unavailable')}${a.error?`<br>${esc(a.error)}`:''}</div></details>`;
      restoreDetailState($('account'));
    }
''' + text[end:]
start = text.index('    function renderLiveMovers(data)')
end = text.index('    function levelTrack(row)', start)
text = text[:start] + '''    function renderLiveMovers(data){
      const movers=data.live_movers||{},modes=movers.modes||{},available=Object.keys(moverModeLabels).filter(key=>Array.isArray(modes[key])),selected=available.includes(moverMode)?moverMode:available[0]||'exec5',rows=modes[selected]||[];moverMode=selected;
      const age=movers.snapshot_age_sec,current=movers.status==='live'&&age!=null&&Number(age)>=0&&Number(age)<=90;
      const controls=`<div class="segmented">${available.map(key=>`<button class="mover-mode ${key===selected?'active':''}" type="button" data-mode="${key}">${esc(moverModeLabels[key])}</button>`).join('')}</div>`;
      $('live-movers').innerHTML=`<div class="section-head"><div><h2>${current?'Observed executable paths':'Historical observed moves'}</h2><div class="subvalue">Separate research census · ${current?'current snapshot':`historical snapshot, ${age==null?'age unknown':`${num(Number(age)/86400,1)} days old`}`} · these are not bot trades or predictions</div></div>${controls}</div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>Pair</th><th>Observed side</th><th>Window</th><th>Net pips</th><th>Net bps</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row.instrument)}</td><td>${esc(row.side||row.direction||'')}</td><td>${num(row.duration_minutes,0)}m</td><td>${signed(row.executable_net_pips,2)}</td><td>${signed(row.move_bps,2)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No retained census rows for this window.</div>'}<div class="overview-note">Historical bid/ask paths include the census cost assumptions. They do not show current opportunities, executed trades or predictive accuracy.</div>`;
    }
    let marketOverviewWindow='15m';
    function renderMarketOverview(data){
      const market=data.market_overview||{},stamp=Number(market.generated_epoch),publicationAge=Date.now()/1000-stamp,publicationCurrent=Number.isFinite(stamp)&&publicationAge>=0&&publicationAge<=90;
      const allRows=Array.isArray(market.rows)?market.rows:[],currentRows=publicationCurrent?allRows.filter(row=>row.status==='current'&&row.quote_age_sec!=null&&Number(row.quote_age_sec)>=0&&Number(row.quote_age_sec)+publicationAge<=60):[];
      const window=marketOverviewWindow,change=row=>row.changes?.[window]||{},rows=[...currentRows].sort((a,b)=>Math.abs(Number(change(b).return_bps||0))-Math.abs(Number(change(a).return_bps||0))).slice(0,10);
      const controls=`<div class="segmented">${['5m','15m','60m'].map(value=>`<button type="button" class="market-window ${value===window?'active':''}" data-window="${value}" aria-pressed="${value===window}">${value==='60m'?'1 hour':value.replace('m',' minutes')}</button>`).join('')}</div>`;
      $('market-overview').innerHTML=`<div class="section-head"><div><h2>Market moves</h2><div class="subvalue">${currentRows.length?`${currentRows.length} current pairs · largest observed ${window} moves`:'Current market prices unavailable'}</div></div>${controls}</div>${rows.length?`<div class="table-wrap"><table class="market-table"><thead><tr><th>Pair</th><th>Mid price</th><th>Change</th><th>Pips</th><th class="optional-column">Spread</th><th class="optional-column">Quote age</th></tr></thead><tbody>${rows.map(row=>{const move=change(row),known=move.return_bps!=null&&Number.isFinite(Number(move.return_bps));return`<tr><td><strong>${esc(String(row.instrument||'').replace('_',' / '))}</strong>${row.tradeable===false?'<div class="subvalue">Not tradeable</div>':''}</td><td>${num(row.mid,String(row.instrument).endsWith('_JPY')?3:5)}</td><td class="${known?cls(move.return_bps):'muted'}">${known?`${signed(Number(move.return_bps)/100,3)}%`:'History unavailable'}</td><td>${known?signed(move.signed_price_change_pips,2):'—'}</td><td class="optional-column">${num(row.spread_pips,2)}p</td><td class="optional-column">${num(Number(row.quote_age_sec)+publicationAge,0)}s</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">Waiting for a fresh, timestamped market snapshot. Historical moves are in the research section below.</div>'}<div class="overview-note">Observed price changes from completed minute history. Gross movement, before trading costs; not a forecast or a trade result.</div>`;
    }
    function renderAvailableSignals(data){
      const market=data.market_overview||{},marketAge=Date.now()/1000-Number(market.generated_epoch),marketCurrent=Number.isFinite(marketAge)&&marketAge>=0&&marketAge<=90;
      const technical=marketCurrent?(market.rows||[]).filter(row=>row.status==='current'&&row.technical&&['current','ready'].includes(row.technical.status)&&row.quote_age_sec!=null&&Number(row.quote_age_sec)+marketAge<=60).slice(0,5):[];
      const forecasts=(data.top_signals||[]).filter(row=>row.signal_is_live===true&&row.signal_age_sec!=null&&Number(row.signal_age_sec)>=0&&Number(row.signal_age_sec)<=Number(row.signal_fresh_sec||90)).slice(0,4);
      const news=data.news_sentiment||{},newsEpoch=Date.parse(news.generated_utc||''),newsAge=(Date.now()-newsEpoch)/1000,newsCurrent=news.fresh===true&&Number.isFinite(newsAge)&&newsAge>=0&&newsAge<=300,newsRows=newsCurrent?(news.top_pairs||[]).slice(0,4):[];
      const technicalBody=technical.map(row=>`<div class="context-row"><strong>${esc(row.instrument)}</strong> · ${esc(String(row.technical.trend_15m||row.technical.trend_5m||'unavailable').replaceAll('_',' '))}<div class="subvalue">5m momentum ${signed(row.technical.momentum_bps_5m,2)} bps · 15m ${signed(row.technical.momentum_bps_15m,2)} bps</div></div>`).join('');
      const forecastBody=forecasts.map(row=>`<div class="context-row"><strong>${esc(row.instrument)}</strong> · ${esc(row.direction||row.direction_state||'neutral')}<div class="subvalue">${esc(row.family||row.model_id||'Research forecast')} · ${num(row.signal_age_sec,0)}s old · research only</div></div>`).join('');
      const newsBody=newsRows.map(row=>{const event=(row.events||[])[0]||{},headline=event.headline||event.title||'';return`<div class="context-row"><strong>${esc(row.instrument)}</strong> · ${esc(row.direction||'neutral')}<div class="subvalue">${headline?esc(headline):`${Number(row.active_event_count||0)} related scored stories`}</div></div>`}).join('');
      $('available-signals').innerHTML=`<div class="section-head"><h2>Signals &amp; context</h2><span class="muted">Available observations and forecasts</span></div><div class="overview-columns"><div><h3>Technical observations</h3>${technicalBody||'<div class="empty">Fresh technical observations unavailable.</div>'}<div class="overview-note">Price momentum describes the market; it is not a calibrated prediction.</div><details class="compact-details" data-state-key="current-bot-forecasts-v3"><summary>Bot forecasts (${forecasts.length} current)</summary>${forecastBody||'<div class="empty">No current bot forecasts available for this snapshot.</div>'}</details></div><div><h3>News &amp; sentiment</h3><div class="subvalue">${newsCurrent?`Updated ${num(newsAge,0)}s ago · context only`:newsAge>300?`Historical snapshot · ${num(newsAge/3600,1)}h old`:'Current news context unavailable'}</div>${newsBody||(newsCurrent?'<div class="empty">No current directional news context reported.</div>':'<div class="empty">Waiting for a fresh, timestamped news summary.</div>')}</div></div>`;
    }
''' + text[end:]
replace("      if(collecting)return{className:'dot collection',text:'Research collection running; study trading disabled'};",
        "      if(collection.forecasting?.blocked)return{className:'dot blocked',text:collection.forecasting.label||'Latest forecast attempt blocked'};\n      if(collecting)return{className:'dot collection',text:'Research collection running; study trading disabled'};")
start = text.index('    function renderCollectionStatus(data)')
end = text.index('    function render(data)', start)
text = text[:start] + '''    function renderCollectionStatus(data){
      const collection=data.collection_status||{},observations=collection.observations||{},warmup=collection.warmup||{},forecast=collection.forecasting||{},retained=collection.model_attempts||{},counts=retained.counts||{},capped=retained.counts_capped||[];
      const phases={waiting_for_tradeable_quote:'Waiting for tradeable quotes',collecting:'Collecting quotes',building_models_while_capturing_quotes:'Building models while collecting quotes'},phase=phases[collection.study_phase]||'Study phase unknown';
      const count=key=>counts[key]==null?'—':`${Number(counts[key])}${capped.includes(key)?'+':''}`,at=epoch=>epoch==null?'unavailable':new Date(Number(epoch)*1000).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});
      const progress=warmup.last_reported_common_bars==null?'Current warm-up progress is not reported.':`Last reported attempt: ${warmup.last_reported_common_bars} / ${warmup.required_common_m1_bars} common minute bars.`;
      const width=warmup.last_reported_common_bars==null?null:Math.max(0,Math.min(100,100*Number(warmup.last_reported_common_bars)/Number(warmup.required_common_m1_bars)));
      const scope=collection.registered_study_trading_enabled===false?'Registered research study: orders and promotion are disabled.':'Registered study trading controls are unknown.';
      const study=observations.study||{},errors=study.reported_cumulative_errors,publicationErrors=study.reported_cumulative_heartbeat_publication_errors,components=['study','quote_stream','account'].map(name=>`${name.replaceAll('_',' ')}: ${observations[name]?.status||'unknown'} (${num(observations[name]?.age_sec,1)}s)`).join(' / ');
      const feed=observations.quote_stream?.current===true?'Feed connected':'Feed status unavailable',label=forecast.label||phase;
      $('collection-status').innerHTML=`<div class="section-head"><h2>Bot activity</h2><span class="muted">Research collection</span></div><div class="bot-summary"><div><strong class="${forecast.blocked?'warn':''}">${esc(label)}</strong><div class="subvalue">${count('attempts')} attempts · ${count('diagnostics')} withheld or failed · ${count('publication')} forecast sets published · ${count('outcomes')} outcomes received</div><div class="overview-note">${esc(progress)}${forecast.latest_attempt_epoch?` Last attempt ${esc(at(forecast.latest_attempt_epoch))}.`:''}${forecast.observation_current===false?' Collector observation is not current; the saved attempt remains visible.':''}</div>${width==null?'':`<div class="collection-progress" role="progressbar" aria-label="Shared minute history at last attempt" aria-valuemin="0" aria-valuemax="335" aria-valuenow="${Number(warmup.last_reported_common_bars)}"><span style="width:${width}%"></span></div>`}</div><div class="bot-tags"><span class="state-pill ${observations.quote_stream?.current===true?'aggressive_shadow':'blocked'}">${esc(feed)}</span><span class="state-pill blocked">${collection.registered_study_trading_enabled===false?'Study orders disabled':'Study authority unknown'}</span></div></div><details class="compact-details" data-state-key="collection-receipt-v3"><summary>Blocker and collection details</summary><div class="detail-body">${esc(collection.label||'Research collection status unknown')}<br>${esc(scope)} ${esc(phase)}.<br>${esc(components)}<br>${esc(warmup.explanation||'Warm-up requirement unavailable.')}<br>Last retained rejection: ${esc(forecast.last_rejection_reason||'none reported')} · ${esc(at(forecast.last_rejection_epoch))}<br>Latest study observation: ${esc(collection.study_reason||'no transient reason')}<br>Reported study errors: ${errors==null?'unknown':errors} total; heartbeat write errors: ${publicationErrors==null?'unknown':publicationErrors} total. Collection status describes recent observations, not forecast success.<br>Attempt ledger: ${esc(retained.status||'unavailable')}${retained.reason?` · ${esc(retained.reason)}`:''}</div></details>`;
    }
''' + text[end:]
replace('renderCollectionStatus(data);renderAccount(data);renderHorizonTop(data);',
        'renderMarketOverview(data);renderAvailableSignals(data);renderCollectionStatus(data);renderAccount(data);renderHorizonTop(data);')
replace("catch(error){$('dot').className='dot';$('status').textContent=`Disconnected / ${error}`}finally{window.setTimeout(refresh,1500)}",
        "catch(error){$('dot').className='dot';$('status').textContent=`Disconnected / ${error}`;renderMarketOverview({});renderAvailableSignals({});renderCollectionStatus({});renderAccount({})}finally{window.setTimeout(refresh,1500)}")
replace("    document.querySelectorAll('.dashboard-tab').forEach", "    document.addEventListener('click',event=>{const button=event.target.closest('button.market-window');if(!button)return;marketOverviewWindow=button.dataset.window||'15m';if(lastMainData)renderMarketOverview(lastMainData)});\n    document.querySelectorAll('.dashboard-tab').forEach")
path.write_text(text, encoding='utf-8', newline='\n')
